export enum TransactionCategory {
  FOOD = "식비",
  DRINK = "음료",
  RECHARGE = "충전",
  CREDIT_CARD_PAYMENT = "카드대금",
  SALARY = "급여",
  SAVINGS = "저금",
  EMERGENCY_FUND = "비상금",
  INVESTMENT = "재테크",
  SHOPPING = "쇼핑",
  INSURANCE = "보험",
  TRANSPORT = "교통비",
  SUBSCRIBE = "구독료",
  PHONE = "통신비",
  DUES = "회비",
  PRESENT = "선물",
  LOAN_REPAYMENT = "상환",
  ETC = "기타",
}
