import {
  Wallet,
  UtensilsCrossed,
  Coffee,
  ShoppingBag,
  Car,
  Repeat,
  Smartphone,
  Shield,
  Users,
  Gift,
  PiggyBank,
  TrendingUp,
  AlertCircle,
  CreditCard,
  Battery,
  ArrowLeftRight,
  MoreHorizontal,
  LucideIcon,
} from "lucide-react";
import { TransactionCategory } from "@/model/transaction.model";

export const categoryIcons: Record<TransactionCategory, LucideIcon> = {
  SALARY: Wallet,
  FOOD: UtensilsCrossed,
  DRINK: Coffee,
  SHOPPING: ShoppingBag,
  TRANSPORT: Car,
  SUBSCRIBE: Repeat,
  PHONE: Smartphone,
  INSURANCE: Shield,
  DUES: Users,
  PRESENT: Gift,
  SAVINGS: PiggyBank,
  INVESTMENT: TrendingUp,
  EMERGENCY_FUND: AlertCircle,
  CREDIT_CARD_PAYMENT: CreditCard,
  RECHARGE: Battery,
  LOAN_REPAYMENT: ArrowLeftRight,
  ETC: MoreHorizontal,
};
