name: Next.js CI/CD

on:
  # push:
  #   branches:
  #     - main
  #     - dev
  # pull_request:
  #   branches:
  #     - main
  #     - dev

jobs:
  check:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm install pnpm@10.4.1

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

  deploy:
    name: Deploy to Production
    needs: check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@10.4.1

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
